blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog_app import views as blogview
from blog_app.feeds import LatestEntriesFeed
from django.conf.urls import (handler400, handler403, handler404, handler500)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog_app.urls')),
    path('', blogview.dashboard, name='dashboard'),
    path('feed/', LatestEntriesFeed(), name='post_feed'),
    path('social-auth/', include('social_django.urls', namespace='social'))
]
handler400= 'blog_app.views.handler404'

blog/blog_app/urls.py
from django.contrib import admin
from django.urls import path
from blog_app import views
from django.contrib.auth import views as auth_views

app_name = 'blog_app'
urlpatterns = [
    path('about',views.AboutView.as_view(),name='about' ),
    path('post/list',views.PostListView.as_view(),name='post_list'),
    path('post/drafts',views.DraftListView.as_view(),name='post_drafts_list'),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/create',views.PostCreateView.as_view(),name='post_create'),
    path('post/<int:pk>/edit',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/delete',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/<int:pk>/comment',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve',views.comment_approve,name='comment_approve'),
    path('comment/<int:pk>/delete',views.comment_remove,name='comment_remove'),
    path('post/<int:pk>/publish',views.post_publish,name='post_publish'),
    path('accounts/login', auth_views.LoginView.as_view(),name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout',kwargs={'next_page':'dashboard'}),
    path('', views.dashboard, name='dashboard'),

]

blog/blog_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import path, reverse, reverse_lazy
from django.contrib import admin
from taggit.managers import TaggableManager

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)
    tags = TaggableManager()
    def publish(self):
        self.publish_date = timezone.now()
        self.save()
    
    def approve_comments(self):
        #restituisce tutti i commenti approvati leggendo
        #la relazione che è definita a livello di Comment
        return self.comments.filter(approved_comments=True)
    
    def get_absolute_url(self):
        print('Nel metodo Absolute URL: ' + str(self.pk))
        return reverse("blog_app:post_detail", kwargs={"pk": self.pk})
    
    
    def __str__(self):
        return self.title + ' - ' +self.author.username    

class Comment(models.Model):
    post = models.ForeignKey('blog_app.Post', related_name='comments', on_delete=models.DO_NOTHING)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comments = models.BooleanField(default=False)

    def approve(self):
        self.approved_comments = True
        self.save()
        
    def get_absolute_url(self):
        return reverse("blog_app:post_list")
    
    def __str__(self):
        return self.text

blog/blog_app/forms.py
from django import forms
from blog_app.models import Comment, Post

class PostForm(forms.ModelForm):
    
    class Meta():
        model = Post
        fields = ('author','title', 'text')
        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class':'editable mdedium-editor-textarea postcontent'}),
        }
        
class CommentForm(forms.ModelForm):
    
    class Meta():
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class':'editable mdedium-editor-textarea postcontent'}),
        }
        
    

blog/blog_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog_app.models import Post, Comment
from blog_app.forms import CommentForm, PostForm
from django.utils import timezone
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.core.mail import send_mail
from taggit.models import Tag
from django.contrib import messages

from django.views.generic import (TemplateView, ListView, 
                                  CreateView, DetailView,
                                  UpdateView, DeleteView)

class AboutView(TemplateView):
    template_name = 'about.html'
    
class PostListView(ListView):
    model = Post
    paginate_by = 2
    def get_queryset(self):
        qs = super().get_queryset()
        return qs


class PostDetailView(DetailView):
    model = Post
    
class PostCreateView(LoginRequiredMixin,CreateView):
    template_name = 'post_form.html'
    form_class = PostForm


class PostUpdateView(LoginRequiredMixin,UpdateView):
    redirect_field_name='post_form.html'
    model = Post
    fields = '__all__'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    #redirect_field_name='post_list.html'
    model = Post
    success_url = reverse_lazy('blog_app:post_list')

class DraftListView(LoginRequiredMixin, ListView):
    template_name='post_drafts_list.html'
    model = Post
    paginate_by = 2

    
    def get_queryset(self):
        qs = super().get_queryset().filter(publish_date__isnull=True).order_by('create_date')
        print('Elementi trovati: ' + str(qs.count()))
        return qs
    
    

###########################################
###########################################
@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog_app:post_detail',pk=post.pk)
    else:
        form = CommentForm()
    return render(request,'comment_form.html',{'form':form})



@login_required   
def comment_approve(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    messages.info(request, 'Commento approvato con successo')
    return redirect('blog_app:post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog_app:post_detail',pk=post_pk)

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    #INVIAMO LA EMAIL DI CONFERMA PUBBLICAZIONE
    messages.info(request, 'Post pubblicato con successo')
    send_mail('subjetc','Messagio','margoneto@publisys.it',('maurizio.argoneto@gmail.com',), fail_silently=True)
    return redirect('blog_app:post_detail', pk=pk)

def dashboard(request):
    return render(request, 'registration/dashboard.html', {'section':'dashboard'})


# HTTP Error 400
def handler404(request, exception):
    return render(request, 'blog_app/404.html', locals())

blog/blog_app/templates/blog_app/about.html
{% extends 'blog_app/base.html' %} {% block title%} About Page {% endblock%} {% block bodyblock%}


<div class="shadow"></div>

<div class='jumbotron'>
    <h2>Pagina di informazione generica</h2>
</div>{%endblock%}

blog/blog_app/templates/blog_app/comment_form.html
{% extends 'blog_app/base.html' %} {% block title%} Comment Form {% endblock%} {% block bodyblock%}


<div class="shadow"></div>

<div class='jumbotron'>
    <h2>Comment Form</h2>
    <h1>New comment</h1>
    <form method="POST" class="post-form">
        {% csrf_token %} {{form.as_p}}
        <button type="submit" class="save btn btn-default">Post Comment</button>
    </form>

    <script>
        var editor = new MediumEditor('.editable');
    </script>
</div>{%endblock%}

blog/blog_app/templates/blog_app/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %} {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

blog/blog_app/templates/blog_app/post_confirm_delete.html
{% extends 'blog_app/base.html' %} {% block title%} Confirm Delete {% endblock%} {% block bodyblock%}


<div class="shadow"></div>

<div class='jumbotron'>
    <form action="" method="post">{% csrf_token %}
        <p>Sicuro di voler cancellare il POST "{{ post.title }}"?</p>
        <input class='btn btn-danger' type="submit" value="Confirm" />
    </form>
</div>{%endblock%}

blog/blog_app/templates/blog_app/post_detail.html
{% extends 'blog_app/base.html' %} {% block title%} Post Detail {% endblock%} {% block bodyblock%}


<div class="shadow"></div>

<div class='jumbotron'>
    <h1 class='posttitle loader'>{{ post.title }}</h1>

    {% include 'messages.html' %} {% if post.publish_date %}
    <div class="date postdate">
        <h3>{{ post.publish_date }}</h3>
    </div>

    {% else %}
    <a class="btn btn-default" href="{% url 'blog_app:post_publish' pk=post.pk %}">Pubblica</a> {% endif %}

    <p class='postcontent'>{{ post.text|safe|linebreaksbr }}</p>


    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog_app:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil">EDIT POST</span></a>
    <a class="btn btn-primary" href="{% url 'blog_app:post_delete' pk=post.pk %}"><span class="glyphicon glyphicon-remove">DELETE POST</span></a> {% endif %}



    <hr>
    <a class="btn btn-primary btn-comment" href="{% url 'blog_app:add_comment_to_post' pk=post.pk %}">Add comment</a>
    <div class="container">


        {% for comment in post.comments.all %}

        <p>{{ comment.text|safe|linebreaks }}</p>
        <p>Posted by: <strong>{{ comment.author }}</strong></p>
        <br> {% if user.is_authenticated %}
        <p>{{ comment.created_date }} </p>
        <p>{% if comment.approved_comments %}</p>
        <a class="btn btn-primary" href="{% url 'blog_app:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove">Remove Comment</span></a>
        <p>{%else%}</p>
        <a class="btn btn-primary" href="{% url 'blog_app:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok">Approve Comment</span></a>
        <p>{% endif %}</p>
        <p>{% endif %}</p>
        {% empty %}
        <p>No comments posted.</p>
        {% endfor %}
    </div>
</div>{%endblock%}

blog/blog_app/templates/blog_app/post_drafts_list.html
{% extends 'blog_app/base.html' %} {% block title%} Post Draft List {% endblock%} {% block bodyblock%}


<div class="shadow"></div>

<div class='jumbotron'>
    <h2>Post Drafts List</h2>
    {% for post in post_list %}
    <div class="post">
        <p class="date">created: {{ post.create_date|date:'d-m-Y' }}</p>
        <h1><a href="{% url 'blog_app:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|truncatechars:200 }}</p>
    </div>
    {% endfor %} {% include "pagination.html" with page=page_obj %}
</div>{%endblock%}

blog/blog_app/templates/blog_app/post_form.html
{% extends 'blog_app/base.html' %} {% block title%} Post Form {% endblock%} {% block bodyblock%}


<div class="shadow"></div>

<div class='jumbotron'>
    <h2>Post Form</h2>
    <form method="POST" class="post-form">
        {% csrf_token %} {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <script>
        var editor = new MediumEditor('.editable');
    </script>
    {% include 'messages.html' %}
</div>{%endblock%}

blog/blog_app/templates/blog_app/post_list.html
{% extends 'blog_app/base.html' %} {% block title%} Post List Page {% endblock%} {% block bodyblock%}


<div class="shadow"></div>

<div class='jumbotron'>
    <h2>Post List Page</h2>
    {% include 'messages.html' %} {% for post in post_list%}

    <div class='post'>
        <h1>
            <a href="{%url 'blog_app:post_detail' pk=post.pk %}">{{post.title}}</a>
        </h1>
        <p>Tags: {{post.tags.all|join:", "}}</p>
        <div class="date">
            <p>Published on: {{post.publish_date | date:"D M Y"}}</p>
        </div>
        <a href="{% url 'blog_app:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
    </div>{%endfor%} {% include "pagination.html" with page=page_obj %}

</div>{%endblock%}

blog/blog_app/templates/pagination.html
<div class="pagination"><span class="step-links">

{% if page.has_previous%}
<a href="?page={{ page.previus_page_number}}">Previouse</a>
{%endif%}
<span class="current">Page {{page.number}} of {{page.paginator.num_pages}}</span> {% if page.has_next%}<a href="?page={{ page.next_page_number}}">Next</a>{%endif%}

    </span>
</div>